trigger:
- main

pr:
- main

jobs:
- deployment: DeployNodeApp
  pool:
    vmImage: 'ubuntu-latest'
  environment: 'my-app-environment'
  strategy:
    runOnce:
      deploy:
        steps:
        - task: DownloadBuildArtifacts@0
          inputs:
            buildType: 'specific'
            project: '<Your_Project_ID>'
            definition: '<Your_Build_Pipeline_ID>'
            buildVersionToDownload: 'latest'
            downloadPath: '$(Pipeline.Workspace)'

        - task: AzureWebApp@1
          inputs:
            azureSubscription: '<Your_Azure_Service_Connection>'
            appName: '<Your_Azure_App_Name>'
            package: '$(Pipeline.Workspace)/drop'

